name: Publish MadCrew.VR Package

on: 
  release:
    types: [published]

jobs:
  gpr-publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create and publish package
      uses: ./.github/actions/actions-gpr-publish
      with:
        npm_registry_url: ${{ secrets.NPM_REGISTRY_URL }}
        npm_auth_token: ${{ secrets.GITHUB_TOKEN }}
        package_directory_path: Assets
        package_type: madcrewvr
